
#include "core.h"


#define STRINGIFY(x) #x

#define SWITCH_CASE_ENUM_TO_STRING(enum_name)                                  \
    case (enum_name) | SHIFT_MASK:                                             \
        return " S " STRINGIFY(enum_name);                                     \
    case (enum_name) | CONTROL_MASK:                                           \
        return "C  " STRINGIFY(enum_name);                                     \
    case (enum_name) | CONTROL_MASK | SHIFT_MASK:                              \
        return "CS " STRINGIFY(enum_name);                                     \
    case (enum_name):                                                          \
        return "   " STRINGIFY(enum_name);


const char* get_pretty_screen_text(immy_screen_t screen) {

    switch (screen) {

    case SCREEN_THUMB_GRID:
        return "SCREEN_THUMB";

    case SCREEN_IMAGE:
        return "SCREEN_IMAGE";

    case SCREEN_FILE_LIST:
        return "SCREEN_FILE_LIST";

    case SCREEN_KEYBINDS:
        return "SCREEN_KEYBINDS";

    case SCREEN_ALL:
        return "SCREEN_ANY";
    }
}

const char* immy_get_interpolation_pretty_text(TextureFilter tf){
    switch (tf) {

    case TEXTURE_FILTER_POINT:
        return "NEAREST_NEIGHBOUR";

    case TEXTURE_FILTER_BILINEAR:
        return "BILINEAR";

    case TEXTURE_FILTER_TRILINEAR:
        return "TRILINEAR";

    case TEXTURE_FILTER_ANISOTROPIC_4X:
        return "ANISOTROPIC_4X";

    case TEXTURE_FILTER_ANISOTROPIC_8X:
        return "ANISOTROPIC_8X";

    case TEXTURE_FILTER_ANISOTROPIC_16X:
        return "ANISOTROPIC_16X";
    }
}


const char* get_key_to_pretty_text(int key) {

    switch (key) {

        SWITCH_CASE_ENUM_TO_STRING(KEY_NULL)
        SWITCH_CASE_ENUM_TO_STRING(KEY_APOSTROPHE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_COMMA)
        SWITCH_CASE_ENUM_TO_STRING(KEY_MINUS)
        SWITCH_CASE_ENUM_TO_STRING(KEY_PERIOD)
        SWITCH_CASE_ENUM_TO_STRING(KEY_SLASH)
        SWITCH_CASE_ENUM_TO_STRING(KEY_ZERO)
        SWITCH_CASE_ENUM_TO_STRING(KEY_ONE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_TWO)
        SWITCH_CASE_ENUM_TO_STRING(KEY_THREE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_FOUR)
        SWITCH_CASE_ENUM_TO_STRING(KEY_FIVE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_SIX)
        SWITCH_CASE_ENUM_TO_STRING(KEY_SEVEN)
        SWITCH_CASE_ENUM_TO_STRING(KEY_EIGHT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_NINE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_SEMICOLON)
        SWITCH_CASE_ENUM_TO_STRING(KEY_EQUAL)
        SWITCH_CASE_ENUM_TO_STRING(KEY_A)
        SWITCH_CASE_ENUM_TO_STRING(KEY_B)
        SWITCH_CASE_ENUM_TO_STRING(KEY_C)
        SWITCH_CASE_ENUM_TO_STRING(KEY_D)
        SWITCH_CASE_ENUM_TO_STRING(KEY_E)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F)
        SWITCH_CASE_ENUM_TO_STRING(KEY_G)
        SWITCH_CASE_ENUM_TO_STRING(KEY_H)
        SWITCH_CASE_ENUM_TO_STRING(KEY_I)
        SWITCH_CASE_ENUM_TO_STRING(KEY_J)
        SWITCH_CASE_ENUM_TO_STRING(KEY_K)
        SWITCH_CASE_ENUM_TO_STRING(KEY_L)
        SWITCH_CASE_ENUM_TO_STRING(KEY_M)
        SWITCH_CASE_ENUM_TO_STRING(KEY_N)
        SWITCH_CASE_ENUM_TO_STRING(KEY_O)
        SWITCH_CASE_ENUM_TO_STRING(KEY_P)
        SWITCH_CASE_ENUM_TO_STRING(KEY_Q)
        SWITCH_CASE_ENUM_TO_STRING(KEY_R)
        SWITCH_CASE_ENUM_TO_STRING(KEY_S)
        SWITCH_CASE_ENUM_TO_STRING(KEY_T)
        SWITCH_CASE_ENUM_TO_STRING(KEY_U)
        SWITCH_CASE_ENUM_TO_STRING(KEY_V)
        SWITCH_CASE_ENUM_TO_STRING(KEY_W)
        SWITCH_CASE_ENUM_TO_STRING(KEY_X)
        SWITCH_CASE_ENUM_TO_STRING(KEY_Y)
        SWITCH_CASE_ENUM_TO_STRING(KEY_Z)
        SWITCH_CASE_ENUM_TO_STRING(KEY_LEFT_BRACKET)
        SWITCH_CASE_ENUM_TO_STRING(KEY_BACKSLASH)
        SWITCH_CASE_ENUM_TO_STRING(KEY_RIGHT_BRACKET)
        SWITCH_CASE_ENUM_TO_STRING(KEY_GRAVE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_SPACE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_ESCAPE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_ENTER)
        SWITCH_CASE_ENUM_TO_STRING(KEY_TAB)
        SWITCH_CASE_ENUM_TO_STRING(KEY_BACKSPACE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_INSERT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_DELETE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_RIGHT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_LEFT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_DOWN)
        SWITCH_CASE_ENUM_TO_STRING(KEY_UP)
        SWITCH_CASE_ENUM_TO_STRING(KEY_PAGE_UP)
        SWITCH_CASE_ENUM_TO_STRING(KEY_PAGE_DOWN)
        SWITCH_CASE_ENUM_TO_STRING(KEY_HOME)
        SWITCH_CASE_ENUM_TO_STRING(KEY_END)
        SWITCH_CASE_ENUM_TO_STRING(KEY_CAPS_LOCK)
        SWITCH_CASE_ENUM_TO_STRING(KEY_SCROLL_LOCK)
        SWITCH_CASE_ENUM_TO_STRING(KEY_NUM_LOCK)
        SWITCH_CASE_ENUM_TO_STRING(KEY_PRINT_SCREEN)
        SWITCH_CASE_ENUM_TO_STRING(KEY_PAUSE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F1)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F2)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F3)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F4)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F5)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F6)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F7)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F8)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F9)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F10)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F11)
        SWITCH_CASE_ENUM_TO_STRING(KEY_F12)
        SWITCH_CASE_ENUM_TO_STRING(KEY_LEFT_SHIFT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_LEFT_CONTROL)
        SWITCH_CASE_ENUM_TO_STRING(KEY_LEFT_ALT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_LEFT_SUPER)
        SWITCH_CASE_ENUM_TO_STRING(KEY_RIGHT_SHIFT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_RIGHT_CONTROL)
        SWITCH_CASE_ENUM_TO_STRING(KEY_RIGHT_ALT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_RIGHT_SUPER)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KB_MENU)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_0)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_1)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_2)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_3)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_4)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_5)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_6)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_7)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_8)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_9)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_DECIMAL)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_DIVIDE)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_MULTIPLY)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_SUBTRACT)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_ADD)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_ENTER)
        SWITCH_CASE_ENUM_TO_STRING(KEY_KP_EQUAL)
        SWITCH_CASE_ENUM_TO_STRING(KEY_BACK)
        // SWITCH_CASE_ENUM_TO_STRING(KEY_MENU)
        SWITCH_CASE_ENUM_TO_STRING(KEY_VOLUME_UP)
        SWITCH_CASE_ENUM_TO_STRING(KEY_VOLUME_DOWN)
    }
    return "UNKNOWN";
}

const char* get_mouse_to_pretty_text(int key) {

    switch (key) {

        SWITCH_CASE_ENUM_TO_STRING(MOUSE_WHEEL_BWD)
        SWITCH_CASE_ENUM_TO_STRING(MOUSE_WHEEL_FWD)

        SWITCH_CASE_ENUM_TO_STRING(MOUSE_BUTTON_LEFT)
        SWITCH_CASE_ENUM_TO_STRING(MOUSE_BUTTON_RIGHT)
        SWITCH_CASE_ENUM_TO_STRING(MOUSE_BUTTON_MIDDLE)
        SWITCH_CASE_ENUM_TO_STRING(MOUSE_BUTTON_SIDE)
        SWITCH_CASE_ENUM_TO_STRING(MOUSE_BUTTON_EXTRA)
        SWITCH_CASE_ENUM_TO_STRING(MOUSE_BUTTON_FORWARD)
        SWITCH_CASE_ENUM_TO_STRING(MOUSE_BUTTON_BACK)
    }
    return "UNKNOWN";
}


